# SPDX-License-Identifier: GPL-3.0-only
# AI-assisted local test example; see ../NOTICE.md.
# Copy outside the repository as mosquitto.conf. Use only on a trusted LAN.
listener 1883
allow_anonymous true
